#config.yaml
---
inventory:
  plugin: SimpleInventory
  options:
    host_file: 'D:\Automatizacion LAB\Estudio de Caso\hosts.yaml'
    group_file: 'D:\Automatizacion LAB\Estudio de Caso\groups.yaml'


runner:
  plugin: threaded
  options:
    num_workers: 5